INSERT INTO ARTIST (name)
VALUES ('Wallem');

INSERT INTO ARTIST (name)
VALUES ('Лёша Свик');

INSERT INTO ARTIST (name)
VALUES ('NЮ');

INSERT INTO ARTIST (name)
VALUES ('Gonopolsky');

INSERT INTO GANRE (name)
VALUES ('Поп');

INSERT INTO ARTISTGENRE (ARTIST_ID, GANRE_ID)
VALUES (1, 2);

INSERT INTO ARTISTGENRE (ARTIST_ID, GANRE_ID)
VALUES (2, 2);

INSERT INTO ARTISTGENRE (ARTIST_ID, GANRE_ID)
VALUES (3, 1);

INSERT INTO ARTISTGENRE (ARTIST_ID, GANRE_ID)
VALUES (4, 3);

INSERT INTO GANRE (name)
VALUES ('Рэп');

INSERT INTO GANRE (name)
VALUES ('Хип-Хоп');

INSERT INTO ALBUM (name, YEAR_OF_RELEASE)
VALUES ('Безумный', '2021-10-11');

INSERT INTO ALBUM (name, YEAR_OF_RELEASE)
VALUES ('Новый альбом', '2019-10-11');

INSERT INTO ALBUM (name, YEAR_OF_RELEASE)
VALUES ('Старый альбом', '2019-09-15');

INSERT INTO ALBUM (name, YEAR_OF_RELEASE)
VALUES ('На ямайке', '2022-05-01');

INSERT INTO ALBUM (name, YEAR_OF_RELEASE)
VALUES ('Свик', '2024-02-03');

INSERT INTO ALBUM (name, YEAR_OF_RELEASE)
VALUES ('Нити', '2020-03-05');

INSERT INTO ARTISTALBUM (ARTIST_ID, ALBUM_ID)
VALUES (2, 3);

INSERT INTO ARTISTALBUM (ARTIST_ID, ALBUM_ID)
VALUES (1, 1);

INSERT INTO ARTISTALBUM (ARTIST_ID, ALBUM_ID)
VALUES (4, 4);

INSERT INTO ARTISTALBUM (ARTIST_ID, ALBUM_ID)
VALUES (2, 3);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('АУ', 320, 2);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Мой родной', 60, 2);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Отпустил', 320, 2);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Останься со мной', 350, 4);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Стальные нити', 430, 4);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Стальные', 320, 5);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Нити', 230, 6);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Я остаюсь', 240, 3);

INSERT INTO TRACK (name, DURATION, ALBUM_ID)
VALUES ('Харизма', 120, 1);

INSERT INTO COLLECTION (name, YEAR_OF_RELEASE)
VALUES ('Союз 30', '2020-05-05');

INSERT INTO COLLECTION (name, YEAR_OF_RELEASE)
VALUES ('Союз 31', '2021-05-05');

INSERT INTO COLLECTION (name, YEAR_OF_RELEASE)
VALUES ('Союз 32', '2022-05-05');

INSERT INTO COLLECTION (name, YEAR_OF_RELEASE)
VALUES ('Союз 33', '2023-05-05');

INSERT INTO TRACKCOLLECTION (TRACK_ID , COLLECTION_ID)
VALUES (1, 1);

INSERT INTO TRACKCOLLECTION (TRACK_ID , COLLECTION_ID)
VALUES (2, 2);

INSERT INTO TRACKCOLLECTION (TRACK_ID , COLLECTION_ID)
VALUES (4, 3);

INSERT INTO TRACKCOLLECTION (TRACK_ID , COLLECTION_ID)
VALUES (5, 4);

INSERT INTO TRACKCOLLECTION (TRACK_ID , COLLECTION_ID)
VALUES (6, 5);





