SELECT name, DURATION 
FROM TRACK
WHERE DURATION = (SELECT MAX(DURATION) FROM TRACK) 

SELECT name
FROM TRACK
WHERE (DURATION / 60) > 3.5

SELECT NAME
from COLLECTION
WHERE YEAR_OF_RELEASE > '2018-01-01' 
	OR YEAR_OF_RELEASE <= '2020-01-01'
	
SELECT NAME
FROM ARTIST
WHERE name NOT LIKE '% %'

SELECT name
from TRACK
WHERE LOWER(name) LIKE '%мой%' or LOWER(name) like '%my%' 